### ISSUE TITLE
Problem Installing Anaconda

### ISSUE THREAD

**Issue by skirwan27** [biof309/spring2019#2]
I have downloaded and installed PyCharm and Git, but I am having trouble installing Anaconda. During the installation I am prompted to install Microsoft VSCode, but when I do I get an error message saying: 

“Please make sure you are connected to the internet!

Check /Users/stuartkirwan/anaconda3/vscode_inst.py.log”

I have tried reconnecting to the internet and still get this error message. It looks like I have already installed “Anaconda Navigator” on my computer from a long time ago. Perhaps this is causing the problem?

**Comment by marskar** [comment]
Hi @skirwan27,

I suggest uninstalling the previous Anaconda installation [as described here](https://docs.anaconda.com/anaconda/install/uninstall/).

There is also a relevant discussion my Slack: https://biof309.slack.com/archives/C6WSGEE6Q/p1538531821000100?thread_ts=1538524458.000100&cid=C6WSGEE6Q

From the error message, I see you are using a UNIX-based system. If anyone using Windows reads this, the above will likely not work for you. If you use Windows, you can try the `deltree` command instead of `rm -rf` [as listed here](https://www.lemoda.net/windows/windows2unix/windows2unix.html) in Anaconda Prompt instead of Terminal.
